[tool.poetry]
name = "sample"
version = "2.0"
description = "This is sample"
authors = ["Manoj"]
license = "5"

[tool.poetry.dependencies]
python = "3.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
